version: '3.8'

services:
  service-a:
    image: service-a
    build:
      context: .
      dockerfile: ./Dockerfile
  service-b:
    image: service-a
    build: .
  service-c:
    image: service-a

